#!/bin/bash

echo "╔════════════════════════════════════════════════════════════╗"
echo "║   🌐 SilverBitcoin Static Dashboards Setup                ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

# Colors
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

# Check if contract is deployed
if [ ! -f "staking-dashboard/contracts/deployment.json" ]; then
    echo -e "${RED}❌ Contract not deployed yet!${NC}"
    echo ""
    echo "Please deploy the contract first:"
    echo "  cd staking-dashboard/contracts"
    echo "  npm install"
    echo "  npm run deploy"
    echo ""
    exit 1
fi

# Get contract address
CONTRACT_ADDRESS=$(grep -o '"address": "[^"]*' staking-dashboard/contracts/deployment.json | cut -d'"' -f4)
echo -e "${GREEN}✅ Contract found: ${CONTRACT_ADDRESS}${NC}"
echo ""

# Ask for RPC URL
echo -e "${BLUE}📡 RPC Configuration${NC}"
echo ""
echo "Choose RPC option:"
echo "  1) Local node (http://localhost:8546)"
echo "  2) Public RPC (http://your-domain.com:8546)"
echo "  3) Custom URL"
echo ""
read -p "Enter choice (1-3): " rpc_choice

case $rpc_choice in
    1)
        RPC_URL="http://localhost:8546"
        ;;
    2)
        read -p "Enter your domain: " domain
        RPC_URL="http://${domain}:8546"
        ;;
    3)
        read -p "Enter custom RPC URL: " RPC_URL
        ;;
    *)
        echo -e "${RED}Invalid choice${NC}"
        exit 1
        ;;
esac

echo -e "${GREEN}✅ RPC URL: ${RPC_URL}${NC}"
echo ""

# Update config files
echo -e "${BLUE}📝 Updating configuration files...${NC}"

# Update staking dashboard config
cat > staking-dashboard-host/config.js << EOF
// Configuration for Staking Dashboard
// Auto-generated by setup script

const CONFIG = {
    RPC_URL: '${RPC_URL}',
    CHAIN_ID: 5200,
    CHAIN_NAME: 'SilverBitcoin',
    CURRENCY_SYMBOL: 'SLVBTC',
    CONTRACT_ADDRESS: '${CONTRACT_ADDRESS}',
    MIN_STAKE: 1
};
EOF

# Update validator dashboard config
cat > validator-dashboard-host/config.js << EOF
// Configuration for Validator Dashboard
// Auto-generated by setup script

const CONFIG = {
    RPC_URL: '${RPC_URL}',
    CHAIN_ID: 5200,
    CHAIN_NAME: 'SilverBitcoin',
    CURRENCY_SYMBOL: 'SLVBTC',
    CONTRACT_ADDRESS: '${CONTRACT_ADDRESS}'
};
EOF

# Update app.js files to use config
sed -i.bak "s|const CONFIG = {|// CONFIG loaded from config.js\nif (typeof CONFIG === 'undefined') {\n    const CONFIG = {|g" staking-dashboard-host/app.js
sed -i.bak "s|const CONFIG = {|// CONFIG loaded from config.js\nif (typeof CONFIG === 'undefined') {\n    const CONFIG = {|g" validator-dashboard-host/app.js

echo -e "${GREEN}✅ Configuration files updated${NC}"
echo ""

# Create upload package
echo -e "${BLUE}📦 Creating upload packages...${NC}"

# Create staking package
mkdir -p upload-packages/staking
cp staking-dashboard-host/index.html upload-packages/staking/
cp staking-dashboard-host/app.js upload-packages/staking/
cp staking-dashboard-host/config.js upload-packages/staking/

# Create validator package
mkdir -p upload-packages/validator
cp validator-dashboard-host/index.html upload-packages/validator/
cp validator-dashboard-host/app.js upload-packages/validator/
cp validator-dashboard-host/config.js upload-packages/validator/

# Create .htaccess for both
cat > upload-packages/staking/.htaccess << 'EOF'
# Enable CORS
<IfModule mod_headers.c>
    Header set Access-Control-Allow-Origin "*"
    Header set Access-Control-Allow-Methods "GET, POST, OPTIONS"
    Header set Access-Control-Allow-Headers "Content-Type"
</IfModule>

# Gzip compression
<IfModule mod_deflate.c>
    AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css text/javascript application/javascript
</IfModule>

# Browser caching
<IfModule mod_expires.c>
    ExpiresActive On
    ExpiresByType text/html "access plus 1 hour"
    ExpiresByType text/css "access plus 1 month"
    ExpiresByType application/javascript "access plus 1 month"
</IfModule>
EOF

cp upload-packages/staking/.htaccess upload-packages/validator/.htaccess

echo -e "${GREEN}✅ Upload packages created${NC}"
echo ""

# Create README for upload
cat > upload-packages/README.txt << EOF
╔════════════════════════════════════════════════════════════╗
║   📦 SilverBitcoin Dashboards - Upload Instructions        ║
╚════════════════════════════════════════════════════════════╝

STAKING DASHBOARD:
1. Login to Hostinger hPanel
2. Open File Manager
3. Navigate to public_html/
4. Create folder: staking
5. Upload all files from upload-packages/staking/
   - index.html
   - app.js
   - config.js
   - .htaccess

VALIDATOR DASHBOARD:
1. In public_html/
2. Create folder: validator
3. Upload all files from upload-packages/validator/
   - index.html
   - app.js
   - config.js
   - .htaccess

ACCESS:
- Staking: https://silverbitcoin.org/staking
- Validator: https://silverbitcoin.org/validator

CONFIGURATION:
- Contract: ${CONTRACT_ADDRESS}
- RPC URL: ${RPC_URL}
- Chain ID: 5200

TESTING:
1. Open in browser
2. Connect MetaMask
3. Check if validators load
4. Try staking (small amount first)

TROUBLESHOOTING:
- Clear browser cache (Ctrl+F5)
- Check browser console for errors
- Verify RPC URL is accessible
- Ensure MetaMask is on correct network

For more help, see STATIC-DASHBOARDS-README.md
EOF

echo -e "${GREEN}✅ Upload instructions created${NC}"
echo ""

# Summary
echo "╔════════════════════════════════════════════════════════════╗"
echo "║   ✅ Setup Complete!                                       ║"
echo "╠════════════════════════════════════════════════════════════╣"
echo "║   Contract: ${CONTRACT_ADDRESS:0:20}...                    ║"
echo "║   RPC URL: ${RPC_URL:0:40}                                 ║"
echo "╠════════════════════════════════════════════════════════════╣"
echo "║   📦 Upload Packages Ready:                                ║"
echo "║   - upload-packages/staking/                               ║"
echo "║   - upload-packages/validator/                             ║"
echo "╠════════════════════════════════════════════════════════════╣"
echo "║   📝 Next Steps:                                           ║"
echo "║   1. Read upload-packages/README.txt                       ║"
echo "║   2. Upload to Hostinger                                   ║"
echo "║   3. Test in browser                                       ║"
echo "║   4. Share with users!                                     ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo -e "${BLUE}📖 For detailed instructions, see:${NC}"
echo "   STATIC-DASHBOARDS-README.md"
echo ""

echo -e "${GREEN}🎉 Ready to upload to Hostinger!${NC}"
