#!/bin/bash

set -e

# Get the project root directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# Change to project root
cd "$PROJECT_ROOT"

echo "╔════════════════════════════════════════════════════════════╗"
echo "║   🚀 SilverBitcoin Static Staking Setup                   ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
BLUE='\033[0;34m'
NC='\033[0m'

# Check if node is running
echo "📡 Checking SilverBitcoin node..."
if ! curl -s http://localhost:8546 > /dev/null 2>&1; then
    echo -e "${RED}❌ Node is not running on port 8546${NC}"
    echo "Please start your node first"
    exit 1
fi
echo -e "${GREEN}✅ Node is running${NC}"
echo ""

# Check if contract is deployed
if [ ! -f "staking-dashboard/contracts/deployment.json" ]; then
    echo -e "${YELLOW}⚠️  Contract not deployed yet${NC}"
    echo ""
    echo "Deploying contract..."
    cd staking-dashboard/contracts
    
    if [ ! -d "node_modules" ]; then
        echo "Installing dependencies..."
        npm install
    fi
    
    echo "Deploying contract..."
    npm run deploy
    
    if [ $? -ne 0 ]; then
        echo -e "${RED}❌ Contract deployment failed${NC}"
        exit 1
    fi
    
    echo ""
    echo "Registering validators..."
    npm run register
    
    cd ../..
fi

# Get contract address
CONTRACT_ADDRESS=$(grep -o '"address": "[^"]*' staking-dashboard/contracts/deployment.json | cut -d'"' -f4)
echo -e "${GREEN}✅ Contract: ${CONTRACT_ADDRESS}${NC}"
echo ""

# Ask for RPC URL
echo -e "${BLUE}📡 RPC Configuration${NC}"
echo ""
echo "Choose RPC option:"
echo "  1) Local node (http://localhost:8546)"
echo "  2) Public RPC (http://your-domain.com:8546)"
echo "  3) Custom URL"
echo ""
read -p "Enter choice (1-3): " rpc_choice

case $rpc_choice in
    1)
        RPC_URL="http://localhost:8546"
        ;;
    2)
        read -p "Enter your domain: " domain
        RPC_URL="http://${domain}:8546"
        ;;
    3)
        read -p "Enter custom RPC URL: " RPC_URL
        ;;
    *)
        echo -e "${RED}Invalid choice${NC}"
        exit 1
        ;;
esac

echo -e "${GREEN}✅ RPC URL: ${RPC_URL}${NC}"
echo ""

# Update config.js
echo -e "${BLUE}📝 Updating config.js...${NC}"

cat > staking-dashboard-host/config.js << EOF
// SilverBitcoin Staking Dashboard Configuration
// Auto-generated by setup script

const CONFIG = {
    // Your SilverBitcoin node RPC URL
    RPC_URL: '${RPC_URL}',
    
    // SilverBitcoin network details
    CHAIN_ID: 5200,
    CHAIN_NAME: 'SilverBitcoin',
    CURRENCY_SYMBOL: 'SLVBTC',
    
    // Smart contract address (auto-filled)
    CONTRACT_ADDRESS: '${CONTRACT_ADDRESS}',
    
    // Minimum stake amount
    MIN_STAKE: 1
};

// Export for use in app.js
if (typeof module !== 'undefined' && module.exports) {
    module.exports = CONFIG;
}
EOF

echo -e "${GREEN}✅ Config updated${NC}"
echo ""

# Create upload package
echo -e "${BLUE}📦 Creating upload package...${NC}"

mkdir -p upload-package/staking
cp staking-dashboard-host/index.html upload-package/staking/
cp staking-dashboard-host/styles.css upload-package/staking/
cp staking-dashboard-host/app.js upload-package/staking/
cp staking-dashboard-host/config.js upload-package/staking/

# Create .htaccess
cat > upload-package/staking/.htaccess << 'EOF'
# Enable CORS
<IfModule mod_headers.c>
    Header set Access-Control-Allow-Origin "*"
    Header set Access-Control-Allow-Methods "GET, POST, OPTIONS"
    Header set Access-Control-Allow-Headers "Content-Type"
</IfModule>

# Gzip compression
<IfModule mod_deflate.c>
    AddOutputFilterByType DEFLATE text/html text/plain text/xml text/css text/javascript application/javascript
</IfModule>

# Browser caching
<IfModule mod_expires.c>
    ExpiresActive On
    ExpiresByType text/html "access plus 1 hour"
    ExpiresByType text/css "access plus 1 month"
    ExpiresByType application/javascript "access plus 1 month"
</IfModule>
EOF

echo -e "${GREEN}✅ Upload package created${NC}"
echo ""

# Create README
cat > upload-package/README.txt << EOF
╔════════════════════════════════════════════════════════════╗
║   📦 SilverBitcoin Staking Dashboard - Upload Package     ║
╚════════════════════════════════════════════════════════════╝

UPLOAD TO HOSTINGER:
1. Login to Hostinger hPanel
2. Open File Manager
3. Navigate to public_html/
4. Create folder: staking
5. Upload all files from upload-package/staking/
   - index.html
   - styles.css
   - app.js
   - config.js
   - .htaccess

ACCESS:
https://silverbitcoin.org/staking

CONFIGURATION:
- Contract: ${CONTRACT_ADDRESS}
- RPC URL: ${RPC_URL}
- Chain ID: 5200

TESTING:
1. Open in browser
2. Connect MetaMask
3. Check if validators load
4. Try staking (small amount first)

TROUBLESHOOTING:
- Clear browser cache (Ctrl+F5)
- Check browser console for errors
- Verify RPC URL is accessible
- Ensure MetaMask is on correct network

For more help, see staking-dashboard-host/SETUP-GUIDE.md
EOF

echo -e "${GREEN}✅ README created${NC}"
echo ""

# Summary
echo "╔════════════════════════════════════════════════════════════╗"
echo "║   ✅ Setup Complete!                                       ║"
echo "╠════════════════════════════════════════════════════════════╣"
echo "║   Contract: ${CONTRACT_ADDRESS:0:20}...                    ║"
echo "║   RPC URL: ${RPC_URL:0:40}                                 ║"
echo "╠════════════════════════════════════════════════════════════╣"
echo "║   📦 Upload Package Ready:                                 ║"
echo "║   upload-package/staking/                                  ║"
echo "╠════════════════════════════════════════════════════════════╣"
echo "║   📝 Next Steps:                                           ║"
echo "║   1. Read upload-package/README.txt                        ║"
echo "║   2. Upload to Hostinger                                   ║"
echo "║   3. Test in browser                                       ║"
echo "║   4. Share with users!                                     ║"
echo "╚════════════════════════════════════════════════════════════╝"
echo ""

echo -e "${BLUE}📖 For detailed instructions, see:${NC}"
echo "   staking-dashboard-host/SETUP-GUIDE.md"
echo ""

echo -e "${GREEN}🎉 Ready to upload to Hostinger!${NC}"
